#!/bin/sh
echo "==================================="

BOXMODEL=$(cat /etc/hostname 2>/dev/null || echo "unknown")
printf "Device Model : %s\033\n" "$BOXMODEL"
if command -v python3 >/dev/null 2>&1; then
    PYVER=$(python3 --version 2>&1)
elif command -v python >/dev/null 2>&1; then
    PYVER=$(python --version 2>&1)
else
    PYVER="Python: Not installed"
fi
echo "Version: $PYVER"
sleep 1
echo "==================================="
sleep 1
echo "enigma2-plugin-extensions-foreca4 was installed successfully "
sleep 2
set +e
exit 0

