#!/bin/sh
echo "Installing Foreca 4 v.1.3.4 by Evg77734 2025 ↓      "

status='/var/lib/opkg/status'
package='enigma2-plugin-extensions-foreca4'

if grep -q $package $status; then
opkg remove $package > /dev/null 2>&1
fi

if [ -d /usr/lib/enigma2/python/Plugins/Extensions/Foreca4 ] ; then
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/Foreca4  > /dev/null 2>&1
fi

if [ -d /control ] ; then
rm -rf /control  > /dev/null 2>&1
fi
if [ -d /CONTROL ] ; then
rm -rf /CONTROL  > /dev/null 2>&1
fi
if [ -f /control ] ; then
rm -rf /control  > /dev/null 2>&1
fi
exit 0
